import { MCAT_SECTIONS } from "../../js/demoData.js";

function mk(si, topic, subtopic, stems, correct, distractors, wrongExps, explanation, takeaway, trap, related = [], formulas = []) {
  return { section: MCAT_SECTIONS[si], topic, subtopic, stems, correct, distractors, wrong_explanations: wrongExps, explanation, takeaway, trap, related, formulas };
}

export const bioBiochemConcepts = [

  mk(2,"Biochemistry","Enzyme Kinetics",[
    "An enzyme's velocity vs. [S] curve is sigmoidal rather than hyperbolic, and oxygen binding to hemoglobin follows the same pattern. Which kinetic property produces this shape?",
    "A toxin that mimics the substrate binds the active site of one subunit of a tetrameric enzyme, making other subunits bind substrate more tightly. Which term describes this behavior?",
  ],
  "positive cooperativity, in which binding of one substrate molecule increases the affinity of remaining subunits, producing a sigmoidal v vs. [S] curve",
  ["competitive inhibition, which raises Km and could produce apparent sigmoidal kinetics at low inhibitor concentrations",
   "negative cooperativity, in which each successive binding event decreases affinity, producing a flatter Michaelis-Menten curve",
   "uncompetitive inhibition, which shifts both Km and Vmax equally and could appear sigmoidal on a linear plot"],
  ["Competitive inhibition produces the standard hyperbolic Michaelis-Menten curve with increased Km; it does not cause cooperativity",
   "Negative cooperativity produces an even flatter hyperbolic curve, not a sigmoidal one; positive cooperativity is required for sigmoidal kinetics",
   "Uncompetitive inhibition produces parallel Lineweaver-Burk lines; it does not generate a sigmoidal curve"],
  "Allosteric enzymes with multiple subunits display cooperativity. Positive cooperativity: one substrate bound increases others' affinity → sigmoidal curve. Quantified by Hill coefficient n > 1 (hemoglobin ~2.8).",
  "Sigmoidal v vs [S] = positive cooperativity. Hill coefficient > 1. Hemoglobin is the classic example.",
  "Assuming any allosteric enzyme must be inhibited; allostery includes both activation (positive cooperativity) and inhibition.",
  ["Michaelis-Menten kinetics","Hemoglobin O₂ binding"],["v = Vmax[S]ⁿ/(K₀.₅ⁿ + [S]ⁿ)"]),

  mk(2,"Biochemistry","Enzyme Kinetics",[
    "Aspirin irreversibly acetylates COX-1 and COX-2. Even after aspirin is cleared from plasma, platelet COX activity does not recover for days. Why?",
    "DFMO (difluoromethylornithine) permanently inactivates ornithine decarboxylase by covalently modifying the active site. How does this differ from competitive inhibition kinetically?",
  ],
  "irreversible inhibition covalently modifies the active site, so activity recovers only when new enzyme protein is synthesized, not when inhibitor concentration falls",
  ["the drug accumulates in tissues and continues to act even after plasma clearance, mimicking irreversibility",
   "aspirin inhibits prostaglandin synthesis by reducing substrate concentration rather than by enzyme modification",
   "competitive inhibitors at very high concentrations can also covalently bind and produce the same effect"],
  ["Tissue accumulation could slow recovery but does not explain platelet COX: platelets lack nuclei and cannot synthesize new protein, so any inactivation is permanent for the platelet's lifetime",
   "Aspirin directly acetylates serine in the COX active site; it does not reduce arachidonic acid substrate levels",
   "Competitive inhibitors bind reversibly by definition; covalent bond formation is the defining feature of irreversible inhibition, regardless of inhibitor concentration"],
  "Irreversible inhibitors form covalent bonds with enzyme (often serine or cysteine residues). Vmax decreases permanently because fewer functional enzyme molecules exist. Adding excess substrate cannot rescue activity. Recovery requires new enzyme synthesis.",
  "Irreversible inhibition: covalent bond → permanent Vmax loss → no rescue by excess substrate.",
  "Confusing 'not reversible at physiological conditions' with 'not reversible ever'; some covalent inhibitors can be hydrolyzed.",
  ["Suicide substrates","COX inhibitors","Serine proteases"],[]),

  mk(2,"Biochemistry","Protein Structure",[
    "In an α-helix, hydrogen bonds form between which atoms, and what is the approximate pitch of the helix?",
    "A protein is heated to 80°C and loses its enzymatic activity. Upon cooling, activity is fully restored. Which level of structure was disrupted?",
  ],
  "the backbone NH of residue n+4 hydrogen bonds to the backbone C=O of residue n, with 3.6 residues per turn and a rise of 0.54 nm per turn",
  ["side-chain atoms hydrogen bond to one another every three residues, producing the helical geometry",
   "hydrogen bonds form between adjacent backbone atoms in the same residue, generating the helical repeat",
   "the α-helix is stabilized by disulfide bonds every 3.6 residues rather than hydrogen bonds"],
  ["Side chains project outward from the helix and do not form the H-bonds that create helical structure; backbone atoms are the H-bond partners",
   "H-bonds span four residues (n to n+4), not between atoms within the same residue",
   "Disulfide bonds stabilize tertiary structure between cysteines; the α-helix backbone H-bond is the defining structural feature"],
  "α-helix: backbone N–H of residue i+4 donates H-bond to backbone C=O of residue i. 3.6 amino acids per turn, 0.15 nm rise per residue. Right-handed. Proline disrupts because its N has no H to donate.",
  "α-helix: i to i+4 backbone H-bonds; 3.6 residues/turn; proline = helix breaker.",
  "Thinking side chains form the helix H-bonds; the backbone (not side chains) creates the α-helix.",
  ["β-sheet","Protein folding","Ramachandran plot"],[]),

  mk(2,"Biochemistry","Protein Structure",[
    "A mutant protein has all buried hydrophobic residues replaced with charged residues. Which structural property is most directly disrupted?",
    "Urea at high concentrations (8 M) denatures most proteins. Which non-covalent interactions does urea primarily disrupt?",
  ],
  "the hydrophobic core: burying nonpolar residues away from water is the primary thermodynamic driver of protein folding, and replacing them with charged residues destabilizes the native tertiary structure",
  ["the primary structure, because amino acid substitutions change the covalent sequence",
   "disulfide bonds, because charged residues compete with cysteine pairs for reducing equivalents",
   "peptide bonds, because hydrophobic residues are needed to shield peptide bonds from hydrolysis"],
  ["Primary structure refers to covalent peptide bond sequence; replacing one residue type with another changes composition but not covalent backbone connectivity",
   "Disulfide bonds are covalent bonds between cysteines and are not affected by changing other residues to charged ones",
   "Peptide bonds are stable covalent linkages; they are not shielded by hydrophobic residues and are not hydrolyzed under physiological conditions"],
  "The hydrophobic effect is the dominant force in protein folding. Nonpolar residues in aqueous solution force ordered water shells (entropy cost). Burying them in the protein core releases that water, gaining entropy. Disrupting the core by adding polar residues eliminates this driving force.",
  "Hydrophobic core: burying nonpolar side chains drives folding. Disrupting it destabilizes tertiary structure.",
  "Assuming electrostatic interactions are the primary folding force; the hydrophobic effect is thermodynamically dominant.",
  ["Entropy of folding","Chaperones","Denaturation"],[]),

  mk(2,"Biochemistry","Protein Structure",[
    "A chaperone protein (Hsp70) binds exposed hydrophobic patches on a newly synthesized polypeptide. What is the primary function of this interaction?",
    "A patient with a genetic defect in Hsp60 (GroEL homolog) presents with aggregated proteins in mitochondria. Which chaperone function is absent?",
  ],
  "chaperones prevent premature or incorrect aggregation by shielding exposed hydrophobic patches until the polypeptide can fold into its correct native conformation",
  ["chaperones provide the energy for protein folding by hydrolyzing ATP to covalently rearrange disulfide bonds",
   "chaperones add signal peptides to direct proteins to the correct cellular compartment after folding",
   "chaperones degrade misfolded proteins through proteasomal targeting by ubiquitinating exposed hydrophobic regions"],
  ["While Hsp70 uses ATP hydrolysis to cycle substrate binding, ATP energy prevents aggregation — it does not covalently rearrange disulfide bonds; isomerases do that",
   "Signal peptides are encoded in the mRNA sequence and co-translationally threaded through translocons; chaperones assist folding, not targeting signal addition",
   "Ubiquitination by E3 ligases marks misfolded proteins; chaperones are a first line of defense preventing misfolding before ubiquitination becomes necessary"],
  "Hsp70 (cytosol) and Hsp60 (mitochondria/GroEL): prevent aggregation by binding hydrophobic patches exposed during translation or stress. ATP hydrolysis drives conformational cycles that allow repeated attempts at proper folding. Hsp90 stabilizes client proteins (steroid receptors, kinases).",
  "Chaperones: prevent aggregation by binding exposed hydrophobic patches. ATP-driven cycles give polypeptide repeated folding attempts.",
  "Thinking chaperones fold proteins by adding energy; they prevent aggregation and give time for spontaneous folding.",
  ["Protein folding thermodynamics","Hsp90","Ubiquitin-proteasome system"],[]),

  mk(2,"Biochemistry","Metabolism",[
    "Gluconeogenesis is active during prolonged fasting. Which step is catalyzed by pyruvate carboxylase, and why must this reaction occur in the mitochondria?",
    "A patient with a deficiency in PEPCK cannot synthesize glucose from pyruvate. Which step is blocked, and what metabolic consequence results during fasting?",
  ],
  "pyruvate carboxylase converts pyruvate to oxaloacetate (OAA) in the mitochondria, using biotin to add CO₂; OAA is then exported as malate or aspartate because the mitochondrial membrane is impermeable to OAA",
  ["pyruvate carboxylase converts OAA to PEP in the cytosol, the rate-limiting step of gluconeogenesis",
   "pyruvate carboxylase converts pyruvate to acetyl-CoA, which then enters gluconeogenesis through the TCA cycle",
   "pyruvate carboxylase is a cytosolic enzyme that bypasses the mitochondrial membrane by transporting pyruvate directly"],
  ["PEPCK (not pyruvate carboxylase) converts OAA to PEP; these are sequential but distinct enzymes at different steps",
   "Pyruvate → acetyl-CoA is catalyzed by pyruvate dehydrogenase, not pyruvate carboxylase; acetyl-CoA cannot enter gluconeogenesis",
   "Pyruvate carboxylase is mitochondrial; OAA cannot cross the inner mitochondrial membrane so it is converted to malate or aspartate for export"],
  "Gluconeogenesis unique steps: pyruvate → OAA (pyruvate carboxylase, mitochondria, biotin) → PEP (PEPCK, cytosol); fructose-1,6-BP → F6P (FBPase-1); G6P → glucose (glucose-6-phosphatase, ER). These bypass irreversible glycolytic steps.",
  "Gluconeogenesis bypasses: pyruvate carboxylase → PEPCK; FBPase-1; glucose-6-phosphatase.",
  "Confusing pyruvate carboxylase (pyruvate → OAA) with PEPCK (OAA → PEP); they are sequential enzymes.",
  ["Cori cycle","Glycolysis","Anaplerosis"],["ΔG°' = +0.5 kJ/mol (PC); biotin cofactor"]),

  mk(2,"Biochemistry","Metabolism",[
    "A patient with G6PD deficiency develops hemolytic anemia after eating fava beans. Which metabolic pathway is impaired, and what protective molecule is depleted?",
    "A cell under oxidative stress needs NADPH to regenerate glutathione. Which metabolic pathway is the primary cytosolic source of NADPH?",
  ],
  "the pentose phosphate pathway (PPP) is impaired; G6PD catalyzes the first committed step generating NADPH, which is required to reduce oxidized glutathione and protect red blood cells from oxidative damage",
  ["glycolysis is impaired because G6P cannot enter the glycolytic pathway, reducing ATP and causing RBC lysis",
   "the TCA cycle is impaired because NADPH from the cycle is depleted, preventing mitochondrial antioxidant defenses",
   "fatty acid oxidation is impaired because NADPH is needed as a cofactor for the β-oxidation spiral"],
  ["G6PD deficiency does not impair glycolysis; G6P can still proceed through glycolysis; the block is specifically in the PPP branch",
   "The TCA cycle produces NADH for the ETC, not NADPH; cytosolic NADPH for antioxidant defense comes primarily from the PPP",
   "Fatty acid oxidation uses FAD and NAD⁺, not NADPH; NADPH is used in fatty acid synthesis and antioxidant pathways"],
  "The pentose phosphate pathway: G6P → 6-phosphogluconolactone → … generating 2 NADPH per G6P. NADPH reduces oxidized glutathione (GSSG → GSH) via glutathione reductase. GSH protects cells from H₂O₂. Without G6PD, RBCs cannot regenerate GSH → oxidative damage → hemolysis.",
  "PPP: G6PD generates NADPH → regenerates glutathione (GSH) → antioxidant protection. G6PD deficiency → oxidative hemolysis.",
  "Confusing NADPH (from PPP, used for biosynthesis/antioxidants) with NADH (from glycolysis/TCA, used for ETC).",
  ["Fatty acid synthesis","Glutathione","Reactive oxygen species"],[]),

  mk(2,"Biochemistry","Lipid Metabolism",[
    "Malonyl-CoA accumulates when fatty acid synthesis is active. How does this regulate fatty acid oxidation?",
    "A fasting patient has elevated plasma free fatty acids. Acetyl-CoA carboxylase activity is low. Which metabolic consequence follows directly?",
  ],
  "malonyl-CoA inhibits carnitine acyltransferase I (CPT-I), the enzyme that transfers fatty acyl groups across the inner mitochondrial membrane, preventing simultaneous synthesis and oxidation of fatty acids",
  ["malonyl-CoA activates hormone-sensitive lipase, increasing lipolysis and creating a futile cycle of synthesis and breakdown",
   "malonyl-CoA inhibits acetyl-CoA carboxylase by product inhibition, slowing further fatty acid synthesis but not affecting oxidation",
   "malonyl-CoA is converted to acetyl-CoA by decarboxylation in the mitochondria, depleting substrate for β-oxidation"],
  ["Hormone-sensitive lipase is regulated by glucagon/epinephrine (via cAMP/PKA), not by malonyl-CoA directly",
   "Product inhibition of ACC by malonyl-CoA does occur but the key regulation described is CPT-I inhibition that prevents β-oxidation, not just feedback on synthesis",
   "Malonyl-CoA is a cytosolic substrate for fatty acid synthase; it does not enter mitochondria and is not a β-oxidation substrate"],
  "Fatty acid synthesis (cytosol) and β-oxidation (mitochondria) must not occur simultaneously. Malonyl-CoA (made by ACC when energy is high) inhibits CPT-I → fatty acyl groups cannot enter mitochondria → β-oxidation halted. When fasting, ACC is inactive → malonyl-CoA falls → CPT-I active → β-oxidation proceeds.",
  "Malonyl-CoA inhibits CPT-I → prevents fatty acid entry into mitochondria → switches off β-oxidation when synthesis is active.",
  "Forgetting that the key regulatory point is CPT-I (transport into mitochondria), not ACC or β-oxidation enzymes directly.",
  ["β-oxidation","Ketogenesis","Citrate shuttle"],["Malonyl-CoA = CPT-I inhibitor"]),

  mk(2,"Biochemistry","Lipid Metabolism",[
    "Palmitate (C16:0) undergoes complete β-oxidation. How many cycles of β-oxidation occur, and what are the direct products per cycle?",
    "A researcher inhibits HMG-CoA reductase with a statin. Which metabolic pathway is directly blocked, and what is the immediate consequence for LDL receptor expression?",
  ],
  "7 cycles of β-oxidation produce 7 FADH₂, 7 NADH, and 8 acetyl-CoA from one molecule of palmitate",
  ["8 cycles produce 8 FADH₂, 8 NADH, and 8 acetyl-CoA because 16 carbons yield 8 two-carbon units",
   "7 cycles produce 7 FADH₂, 7 NADH, and 7 acetyl-CoA because each cycle removes one acetyl-CoA",
   "6 cycles produce 6 FADH₂, 6 NADH, and 8 acetyl-CoA because palmitate is partially oxidized"],
  ["C16 palmitate requires 7 cuts (not 8) to generate 8 acetyl-CoA: each cycle cleaves one acetyl-CoA from the chain, and the last cycle yields two acetyl-CoA simultaneously",
   "Each cycle yields 1 FADH₂, 1 NADH, and 1 acetyl-CoA; 7 cycles yield 7 of each, but the final cycle releases 2 acetyl-CoA (8 total)",
   "Palmitate undergoes complete oxidation in 7 cycles; partial oxidation is not the normal fate of palmitate in β-oxidation"],
  "Palmitate (16C): 7 cycles of β-oxidation. Each cycle: 1 FADH₂ + 1 NADH + 1 acetyl-CoA. Last cycle yields 2 acetyl-CoA. Totals: 7 FADH₂ + 7 NADH + 8 acetyl-CoA → ~106 ATP net (subtract 2 for activation).",
  "Palmitate β-oxidation: 7 cycles → 7 FADH₂ + 7 NADH + 8 acetyl-CoA. Formula: (n/2 − 1) cycles for saturated fatty acid.",
  "Counting 8 cycles instead of 7; the last cycle produces 2 acetyl-CoA so one fewer cut is needed.",
  ["Fatty acid synthesis","Ketogenesis","ETC ATP yield"],["Cycles = n/2 − 1 for saturated; n = carbon number"]),

  mk(2,"Biochemistry","Metabolism",[
    "A patient with liver failure cannot perform transamination. Which clinical consequence most directly results from impaired alanine aminotransferase (ALT) activity?",
    "Serum ALT and AST are elevated after myocardial infarction and liver injury respectively. Why do these enzymes appear in blood during tissue damage?",
  ],
  "transamination transfers amino groups from amino acids to α-ketoglutarate, producing glutamate; without ALT, alanine cannot contribute its nitrogen to the urea cycle, impairing nitrogen disposal",
  ["without ALT, alanine cannot be converted to glucose via gluconeogenesis because the alanine cycle requires pyruvate, which is blocked",
   "ALT deficiency prevents oxidative phosphorylation because alanine donates electrons directly to Complex I",
   "impaired ALT activity causes ammonia accumulation equivalent to urea cycle enzyme deficiencies because ALT is the entry point to the urea cycle"],
  ["Alanine → pyruvate (via ALT) does feed gluconeogenesis; however, the more direct consequence described is nitrogen disposal impairment, as gluconeogenesis can also use other substrates",
   "Alanine does not donate electrons to the ETC; its carbon skeleton enters metabolism as pyruvate and its nitrogen enters transamination",
   "The urea cycle begins with carbamoyl phosphate (from NH₄⁺ and CO₂); ALT facilitates nitrogen transfer to glutamate, which is deaminated by GDH to release NH₄⁺; ALT is upstream of but distinct from the urea cycle itself"],
  "Transamination (ALT, AST): amino group transferred from amino acid → α-ketoglutarate → glutamate. Glutamate dehydrogenase releases NH₄⁺ for urea cycle. ALT is liver-specific; AST is in liver and heart. Elevated serum ALT/AST = cell lysis releasing intracellular enzymes.",
  "Transamination: amino acids → glutamate → NH₄⁺ → urea cycle. ALT elevated = liver damage. AST elevated = liver or cardiac damage.",
  "Thinking ALT directly participates in the urea cycle; it funnels nitrogen to glutamate, which is then deaminated upstream of the cycle.",
  ["Urea cycle","Gluconeogenesis","Liver function tests"],[]),

  mk(2,"Biochemistry","TCA Cycle",[
    "A researcher uses ¹³C-labeled acetate to trace carbons through the TCA cycle. After one complete turn, which molecule contains the labeled carbons?",
    "α-Ketoglutarate dehydrogenase is inhibited by arsenite. Which TCA intermediates accumulate, and which products are reduced?",
  ],
  "after one turn of the TCA cycle, the labeled carbons from acetyl-CoA are not lost as CO₂ but are found in oxaloacetate (they leave as CO₂ in the second turn)",
  ["the labeled carbons are released as CO₂ in the first turn because the two decarboxylation steps remove all acetyl-CoA carbons",
   "the labeled carbons appear in citrate after one turn because citrate is the first product of acetyl-CoA condensation",
   "the labeled carbons are incorporated into NADH and exit via the electron transport chain"],
  ["The two CO₂ releases in the first turn come from the OAA carbons, not from the newly added acetyl-CoA carbons; acetyl-CoA carbons are retained in OAA after the first turn",
   "Labeled carbons enter citrate at the start but then travel through the cycle; after one full turn they are found in regenerated OAA, not in citrate",
   "NADH carries electrons (hydride), not carbon atoms; the labeled carbons are tracked through carbon-containing intermediates, not coenzymes"],
  "One TCA turn: Acetyl-CoA (2C) + OAA (4C) → citrate (6C) → isocitrate → α-KG (5C) + CO₂ [from OAA carbon] → succinyl-CoA (4C) + CO₂ [from OAA carbon] → … → OAA. Labeled acetyl-CoA carbons are in OAA after one turn; they exit as CO₂ only in the second turn.",
  "Acetyl-CoA carbons are NOT lost as CO₂ in the first TCA turn — they appear in OAA and are released as CO₂ in the second turn.",
  "Assuming both CO₂ molecules released per turn come from acetyl-CoA; they actually come from OAA carbons in the first turn.",
  ["Oxidative phosphorylation","Gluconeogenesis","Anaplerosis"],[]),

  mk(2,"Biochemistry","Oxidative Phosphorylation",[
    "Dinitrophenol (DNP) was used as a weight-loss drug in the 1930s but caused fatal hyperthermia. Which mechanism explains both its efficacy and its lethal toxicity?",
    "Thermogenin (UCP-1) in brown adipose tissue serves a similar function to DNP. Why is thermogenin physiologically useful while DNP is dangerous?",
  ],
  "DNP is a proton ionophore that dissipates the mitochondrial proton gradient across the inner membrane as heat rather than using it to synthesize ATP, uncoupling electron transport from ATP production",
  ["DNP inhibits Complex IV (cytochrome c oxidase), reducing oxygen consumption and halting electron flow",
   "DNP activates F₀F₁-ATP synthase, causing excess ATP production that stimulates futile metabolic cycles generating heat",
   "DNP oxidizes NADH directly, bypassing the ETC and converting chemical energy to heat without electron transport"],
  ["Uncouplers dissipate the proton gradient without inhibiting electron transport; Complex IV inhibitors (like CN⁻) stop electron flow entirely, which is a different mechanism",
   "DNP reduces, not increases, ATP synthesis by bypassing ATP synthase; it does not activate the synthase",
   "DNP acts on the inner membrane as a mobile proton carrier; it does not directly oxidize NADH or bypass electron transport complexes"],
  "Uncouplers (DNP, thermogenin): carry H⁺ across the inner mitochondrial membrane, dissipating the proton gradient as heat. ETC continues (O₂ consumed), but ATP synthase is bypassed. Net: substrate oxidized → heat instead of ATP. Weight loss occurs because cells burn more fuel to meet ATP demand.",
  "Uncoupler: proton gradient → heat (not ATP). ETC continues. Cells burn more fuel trying to maintain ATP → weight loss + hyperthermia.",
  "Confusing uncouplers with ETC inhibitors; uncouplers allow ETC to run (O₂ still consumed) but prevent ATP synthesis.",
  ["Chemiosmosis","Brown adipose tissue","ETC inhibitors"],[]),

  mk(2,"Molecular Biology","DNA Replication",[
    "During replication, the 3′→5′ exonuclease activity of DNA polymerase III detects and excises a mismatched nucleotide. What is this activity called, and what would happen without it?",
    "A mutation eliminates the 3′→5′ exonuclease activity of Pol III. Compared to wild type, which change in the mutation rate is expected?",
  ],
  "proofreading: the 3′→5′ exonuclease removes incorrectly paired nucleotides immediately after incorporation, reducing the base-pair error rate from ~10⁻⁵ to ~10⁻⁷",
  ["mismatch repair: a separate post-replication system that recognizes and excises mismatched bases over long stretches of newly synthesized DNA",
   "nucleotide excision repair: a repair pathway that removes bulky adducts such as thymine dimers caused by UV radiation",
   "base excision repair: a pathway that removes oxidized or deaminated bases using DNA glycosylases"],
  ["Mismatch repair (MMR) operates post-replication and corrects mismatches missed by proofreading; it is a separate, downstream system, not the exonuclease activity of Pol III itself",
   "Nucleotide excision repair removes helix-distorting lesions such as thymine dimers; it is not the same as the replication proofreading exonuclease",
   "Base excision repair uses glycosylases to flip out and remove damaged bases; it is a post-replication repair pathway distinct from proofreading"],
  "DNA Pol III (E. coli): 5′→3′ synthesis + 3′→5′ proofreading exonuclease. Proofreading improves fidelity ~100-fold. DNA Pol I removes RNA primers using its 5′→3′ exonuclease. Eukaryotic equivalent: Pol δ/ε with PCNA sliding clamp.",
  "Proofreading = 3′→5′ exonuclease of Pol III. Raises fidelity 100×. Loss of proofreading → increased mutation rate.",
  "Confusing proofreading (co-replicational) with mismatch repair (post-replicational); both correct errors but at different stages.",
  ["Telomerase","DNA repair pathways","Mutation types"],["Error rate: ~10⁻⁵ without; ~10⁻⁷ with proofreading"]),

  mk(2,"Molecular Biology","Transcription",[
    "Eukaryotic mRNA is processed before export to the cytoplasm. Which three modifications are added, and what is the function of each?",
    "A mutation in the consensus sequence at the 5′ splice site of an intron prevents spliceosome recognition. What is the most likely consequence for the mRNA?",
  ],
  "a 5′ 7-methylguanosine cap (protects from exonucleases, aids ribosome recognition), a 3′ poly-A tail (stability, nuclear export), and splicing to remove introns (exon-only mRNA)",
  ["the 5′ cap is a poly-A sequence added by RNA Pol II, and the 3′ tail is a methylguanosine for export signaling",
   "introns are removed by ribosomes during translation, and the cap and tail are added after protein synthesis",
   "the 5′ cap is added by DNA ligase and the 3′ tail is a poly-G sequence that blocks premature degradation"],
  ["The 5′ cap is 7-methylguanosine (not poly-A); the 3′ tail is poly-A (not methylguanosine); their positions and identities are reversed in this distractor",
   "Splicing is performed by the spliceosome in the nucleus before translation; ribosomes translate mRNA but do not remove introns",
   "The 5′ cap is added by capping enzymes (not DNA ligase), and the 3′ tail is poly-adenylate, not poly-G"],
  "Pre-mRNA processing (nucleus): (1) 5′ 7-methylguanosine cap (capping enzyme; protection + translation initiation). (2) 3′ poly-A tail (poly-A polymerase; stability + export). (3) Splicing by spliceosome (snRNAs + proteins; removes introns, joins exons). All three required for mature mRNA.",
  "mRNA processing: 5′ cap + 3′ poly-A + splicing. All occur in nucleus before export.",
  "Reversing the cap and tail: 5′ cap = methylguanosine; 3′ tail = poly-A. Not interchangeable.",
  ["Alternative splicing","Translation initiation","Nuclear export"],[]),

  mk(2,"Molecular Biology","Translation",[
    "A ribosome translating an mRNA encounters a premature stop codon introduced by a nonsense mutation. What is the most immediate consequence?",
    "Streptomycin binds the 30S ribosomal subunit and causes misreading of the genetic code. Which aspect of translation is directly disrupted?",
  ],
  "translation terminates prematurely, producing a truncated polypeptide that is typically nonfunctional and may be degraded by nonsense-mediated mRNA decay",
  ["the ribosome stalls but continues translating by frameshifting past the stop codon, producing a longer protein",
   "the nonsense mutation is corrected by tRNA editing activity during translation, restoring the correct amino acid",
   "mRNA is immediately degraded by RNase at the stop codon, preventing any protein from being made"],
  ["Frameshifting occurs with insertions/deletions of non-multiples of 3; a stop codon causes termination, not frameshifting",
   "tRNA editing (aminoacyl-tRNA synthetase proofreading) corrects mischarging, not codon sequences in mRNA; mRNA sequence errors are not corrected during translation",
   "Nonsense-mediated decay (NMD) degrades the mRNA after the premature stop codon is recognized, but a truncated protein is typically made first from the first few codons"],
  "Stop codons (UAA, UAG, UGA) are recognized by release factors (not tRNA), causing ribosome disassembly and polypeptide release. A premature stop codon truncates the protein. Eukaryotes: NMD pathway often degrades mRNAs with premature stops to prevent dominant-negative effects.",
  "Nonsense mutation → premature stop → truncated protein → NMD degrades mRNA. Stop codons: UAA, UAG, UGA.",
  "Confusing nonsense (stop codon) with missense (wrong amino acid) or frameshift (wrong reading frame).",
  ["Genetic code","mRNA surveillance","Release factors"],[]),

  mk(2,"Molecular Biology","Mutations",[
    "UV light causes adjacent thymine residues to form covalent dimers that distort the DNA helix. Which repair pathway removes these lesions?",
    "A patient with xeroderma pigmentosum cannot perform nucleotide excision repair. Which clinical manifestation results from sun exposure?",
  ],
  "nucleotide excision repair (NER) recognizes helix-distorting lesions such as thymine dimers and removes a short oligonucleotide spanning the lesion, followed by resynthesis and ligation",
  ["base excision repair (BER), which uses DNA glycosylases to flip out and remove single damaged bases without recognizing helix distortion",
   "mismatch repair (MMR), which corrects base-pair mismatches introduced during replication by recognizing incorrect Watson-Crick pairing",
   "homologous recombination (HR), which repairs double-strand breaks using the sister chromatid as a template"],
  ["BER removes small, non-helix-distorting lesions (oxidized bases, uracil); it does not recognize or remove thymine dimers",
   "MMR corrects replication errors (mismatched bases) but does not remove covalently linked thymine dimers introduced by UV",
   "HR repairs double-strand breaks (DSBs), which are much more severe lesions than UV-induced thymine dimers; NER handles single-strand lesions"],
  "NER: recognize helix distortion → nick both strands flanking the lesion (12–24 nt oligonucleotide in eukaryotes) → Pol δ fills gap → ligase seals. XP patients lack NER components → thymine dimers accumulate → mutations in oncogenes/tumor suppressors → high skin cancer risk.",
  "NER: removes helix-distorting lesions (thymine dimers, bulky adducts). BER: single damaged bases. MMR: replication mismatches.",
  "Thinking BER handles thymine dimers; BER handles small non-distorting base damage, NER handles helix-distorting lesions.",
  ["Base excision repair","Mismatch repair","p53 and DNA damage"],[]),

  mk(2,"Molecular Biology","Gene Regulation",[
    "A gain-of-function mutation converts a proto-oncogene to an oncogene. Which pattern of inheritance does this type of cancer driver typically follow at the cellular level?",
    "BRCA1 is a tumor suppressor gene. A woman inherits one mutant BRCA1 allele. How many additional mutations are needed to inactivate BRCA1 function in a breast epithelial cell?",
  ],
  "proto-oncogene mutations are dominant at the cellular level — a single mutant allele is sufficient to drive abnormal proliferation because the mutant protein is constitutively active",
  ["proto-oncogene mutations are recessive because both alleles must be mutated before signaling is disrupted",
   "proto-oncogene mutations require a two-hit mechanism identical to tumor suppressors for cancer to develop",
   "proto-oncogene mutations only cause cancer when combined with a germline tumor suppressor loss"],
  ["Oncogene mutations are dominant (gain-of-function); tumor suppressor mutations follow the recessive two-hit model; these two classes work by opposite mechanisms",
   "The two-hit model applies to tumor suppressors (loss-of-function), not oncogenes; oncogene gain-of-function mutations are dominant",
   "While co-mutations often occur in cancer, oncogenes are defined by dominant gain-of-function that alone is sufficient to promote proliferation"],
  "Proto-oncogenes (Ras, Myc, EGFR): gain-of-function → constitutively active → dominant. Tumor suppressors (Rb, p53, BRCA1): loss-of-function → recessive, two-hit model (Knudson). Inherited cancer syndromes: one hit germline + one hit somatic = cancer.",
  "Oncogenes: dominant gain-of-function. Tumor suppressors: recessive loss-of-function (two-hit). One germline + one somatic hit = cancer in TS genes.",
  "Applying the two-hit model to oncogenes; it applies only to tumor suppressors.",
  ["Ras/MAPK pathway","p53","Cell cycle"],[]),

  mk(2,"Cell Biology","Cell Cycle",[
    "A cancer cell has lost p53 function. During S phase, the replication machinery encounters a double-strand break. Which checkpoint response is absent?",
    "Cyclin D is overexpressed in many cancers. Which cell cycle transition does this drive, and which tumor suppressor does it bypass?",
  ],
  "the intra-S and G2/M DNA damage checkpoints mediated by p53 are absent; the cell continues replicating damaged DNA rather than arresting to allow repair or triggering apoptosis",
  ["the spindle assembly checkpoint is absent, causing chromosomes to segregate without proper attachment to spindle fibers",
   "the restriction point in G1 is bypassed because p53 normally triggers differentiation at G1, not checkpoint arrest",
   "the G1/S checkpoint cannot be activated because p53 is needed to synthesize cyclin-dependent kinases"],
  ["The spindle assembly checkpoint is regulated by the APC and BubR1/Mad2 kinetochore surveillance proteins, not by p53; p53 regulates DNA damage checkpoints",
   "The restriction point is controlled by Rb/E2F and mitogens, not by p53 as a differentiation trigger",
   "CDKs are constitutively expressed; cyclins are synthesized and degraded; p53 does not synthesize CDKs but does transcribe p21 (CIP/KIP) to inhibit them"],
  "p53 (guardian of the genome): activated by DNA damage → transcribes p21 (inhibits CDK2/cyclin E) → G1 arrest, or transcribes PUMA/Bax → apoptosis. Loss of p53: cells replicate damaged DNA → mutations accumulate → cancer. Most human cancers have p53 mutations.",
  "p53: DNA damage → p21 → CDK2 inhibition → G1 arrest. Or → apoptosis. Loss = damaged DNA replication → cancer.",
  "Thinking p53 regulates the spindle assembly checkpoint; it regulates DNA damage checkpoints via p21 and apoptotic genes.",
  ["CDKs and cyclins","Rb pathway","Apoptosis"],[]),

  mk(2,"Cell Biology","Apoptosis",[
    "A cell receives a Fas ligand signal from a cytotoxic T lymphocyte. What is the sequence of molecular events leading to apoptosis?",
    "Bcl-2 overexpression in follicular lymphoma prevents cells from undergoing apoptosis. Which pathway does Bcl-2 regulate?",
  ],
  "FasL binds Fas receptor → DISC forms (Fas + FADD + procaspase-8) → caspase-8 activated → executes extrinsic apoptosis cascade via caspase-3/7",
  ["FasL triggers the intrinsic pathway by releasing cytochrome c from mitochondria before activating caspases",
   "FasL activates Bcl-2 family proteins to release cytochrome c, bypassing caspase activation entirely",
   "FasL binding inhibits pro-survival NF-κB signaling, which then allows spontaneous mitochondrial permeabilization"],
  ["The extrinsic pathway initiates at the death receptor (Fas); cytochrome c release characterizes the intrinsic pathway; FasL can cross-activate the intrinsic pathway via Bid cleavage, but the direct extrinsic cascade does not require cytochrome c initially",
   "Bcl-2 opposes (not promotes) cytochrome c release by keeping the mitochondrial membrane intact; FasL does not activate Bcl-2",
   "NF-κB is a survival factor; while its inhibition can sensitize to apoptosis, the primary mechanism of Fas-mediated death is direct caspase-8 activation via DISC"],
  "Extrinsic pathway: FasL/TRAIL → death receptor → DISC (FADD + caspase-8) → caspase cascade. Intrinsic pathway: stress → Bax/Bak (pro-apoptotic) overwhelm Bcl-2/Bcl-xL → cytochrome c release → apoptosome → caspase-9 → caspase-3. Both converge on executioner caspases.",
  "Extrinsic: death receptor → caspase-8. Intrinsic: mitochondria → cytochrome c → caspase-9. Both → caspase-3.",
  "Thinking FasL always triggers the intrinsic pathway; Fas uses the extrinsic pathway via DISC/caspase-8.",
  ["Bcl-2 family","Cytochrome c","Caspase cascade"],[]),

  mk(2,"Cell Biology","Signal Transduction",[
    "EGF binds its receptor (EGFR), causing receptor dimerization and transautophosphorylation on tyrosine residues. What is the next step in the MAPK signaling cascade?",
    "A constitutively active Ras mutation is found in 30% of human cancers. Why does this mutation promote uncontrolled proliferation?",
  ],
  "phosphorylated EGFR recruits Grb2 and Sos (a GEF), which catalyzes GDP→GTP exchange on Ras, activating it to trigger the Raf→MEK→ERK kinase cascade",
  ["phosphorylated EGFR directly activates ERK by phosphorylating it without requiring any intermediate adapter proteins",
   "EGFR phosphorylation activates Gi protein, which inhibits adenylate cyclase and raises cAMP to activate PKA",
   "EGFR activates the JAK-STAT pathway directly by recruiting STAT proteins to phosphotyrosine docking sites"],
  ["ERK is not a direct EGFR substrate; the cascade requires adapter proteins (Grb2/Sos) and Ras as intermediaries before reaching Raf→MEK→ERK",
   "EGFR is a receptor tyrosine kinase, not a GPCR; it does not activate heterotrimeric G proteins; Gi-mediated cAMP reduction is a separate signaling pathway",
   "JAK-STAT is primarily used by cytokine receptors (lacking intrinsic kinase activity); EGFR has its own RTK activity and uses the RAS/MAPK pathway primarily"],
  "RTK/Ras/MAPK: EGF → EGFR dimerization → autophosphorylation → Grb2/Sos recruitment → Ras-GTP → Raf → MEK (MAP2K) → ERK (MAPK) → nuclear transcription factors → proliferation. Constitutively active Ras-GTP drives this without EGF.",
  "RTK cascade: EGF → EGFR-P → Grb2/Sos → Ras-GTP → Raf → MEK → ERK → proliferation.",
  "Skipping the Ras step; students often jump directly from EGFR to ERK, omitting the Grb2/Sos/Ras intermediaries.",
  ["PI3K/Akt pathway","cAMP/PKA pathway","JAK-STAT"],["EGFR → Grb2 → Sos → Ras-GTP → Raf → MEK → ERK"]),

  mk(2,"Cell Biology","Membrane Transport",[
    "The Na⁺/K⁺-ATPase pumps 3 Na⁺ out and 2 K⁺ in per ATP hydrolyzed. Which properties of the resting membrane potential does this create?",
    "A patient is given ouabain, which inhibits Na⁺/K⁺-ATPase. Which secondary effect on intracellular Ca²⁺ is expected via Na⁺/Ca²⁺ exchange?",
  ],
  "the pump creates the Na⁺ gradient (high extracellular) and K⁺ gradient (high intracellular) that establish the resting membrane potential (approximately −70 mV, inside negative) and drive secondary active transport",
  ["the pump generates ATP by moving ions down their concentration gradients, powering cellular work",
   "the pump moves Na⁺ inward and K⁺ outward to depolarize the membrane, preparing action potentials",
   "the electrogenic nature of the pump (3:2 ratio) maintains the resting potential at exactly −55 mV in all excitable cells"],
  ["The Na⁺/K⁺-ATPase consumes ATP to move ions against concentration gradients; it does not generate ATP",
   "The pump moves Na⁺ OUT and K⁺ IN; the high intracellular K⁺ and high extracellular Na⁺ are the gradients it maintains",
   "The pump contributes to the resting potential but the main determinant is K⁺ leak channels; −70 mV is typical for neurons but varies by cell type"],
  "Na⁺/K⁺-ATPase: 3 Na⁺ out / 2 K⁺ in / 1 ATP. Creates [Na⁺] high outside, [K⁺] high inside. Electrogenic (net 1+ charge out per cycle → slight inside-negative contribution). K⁺ leak channels primarily set resting membrane potential at ~−70 mV.",
  "Na⁺/K⁺-ATPase: 3 Na⁺ out, 2 K⁺ in, 1 ATP. Maintains gradients for action potentials, secondary active transport, and resting potential.",
  "Thinking the pump is the primary determinant of −70 mV; K⁺ leak channels set most of the resting potential.",
  ["Action potential","Secondary active transport","Cardiac glycosides"],["E = −61 mV × log([K⁺]out/[K⁺]in)"]),

  mk(2,"Physiology","Cardiovascular",[
    "A patient is given a positive inotropic drug that increases intracellular Ca²⁺ during systole. Which phase of the cardiac action potential is most directly enhanced?",
    "During the absolute refractory period of a ventricular cardiomyocyte, why is it impossible to generate another action potential?",
  ],
  "phase 2 (the plateau phase) is enhanced; L-type Ca²⁺ channels are open during this phase and Ca²⁺ influx triggers calcium-induced calcium release (CICR) from the SR, increasing contractility",
  ["phase 0 (rapid depolarization) is enhanced; Na⁺ channels open wider to increase Ca²⁺ influx during upstroke",
   "phase 4 (resting potential) is enhanced; elevated Ca²⁺ stores at rest increase baseline contractility without any action potential change",
   "phase 3 (repolarization) is enhanced; K⁺ channels opening faster increases Ca²⁺ release from the SR"],
  ["Phase 0 depends on fast voltage-gated Na⁺ channels, not Ca²⁺ channels; positive inotropy involves Ca²⁺ during the plateau phase",
   "Phase 4 is the resting state between action potentials; baseline Ca²⁺ stores are set during the action potential phases, not phase 4 alone",
   "Phase 3 is repolarization via K⁺ channels; accelerating repolarization shortens the action potential and reduces Ca²⁺ influx, which would decrease, not increase, contractility"],
  "Ventricular action potential phases: 0 (fast Na⁺ in → depolarization); 1 (Ito K⁺ out → notch); 2 (Ca²⁺ in via L-type = plateau, Ca²⁺ triggers SR release → contraction); 3 (K⁺ out → repolarization); 4 (resting, −90 mV). The absolute refractory period spans phases 0–3 when Na⁺ channels are inactivated.",
  "Cardiac AP phases: 0=Na⁺ in; 1=K⁺ notch; 2=Ca²⁺ plateau (inotropy); 3=K⁺ repolarization; 4=rest.",
  "Confusing phase 2 (Ca²⁺ plateau, contractility) with phase 0 (Na⁺ upstroke, conduction velocity).",
  ["Frank-Starling law","Automaticity","EKG interpretation"],["Plateau phase 2: L-type Ca²⁺ → CICR → contraction"]),

  mk(2,"Physiology","Cardiovascular",[
    "A patient develops orthostatic hypotension (BP drops when standing). Which reflex normally prevents this, and which stretch receptors initiate it?",
    "A physician gives a patient phenylephrine (α₁ agonist). Blood pressure rises. Via the baroreceptor reflex, which change in heart rate follows?",
  ],
  "the baroreceptor reflex: carotid sinus and aortic arch baroreceptors detect reduced stretch when BP falls → NTS in medulla → increased sympathetic and decreased parasympathetic output → increased HR, SV, and vasoconstriction → restored BP",
  ["the chemoreceptor reflex detects low blood oxygen and triggers vasoconstriction to restore pressure",
   "the Bainbridge reflex responds to low venous return by increasing heart rate via atrial stretch receptors",
   "arterial baroreceptors in the pulmonary vasculature detect pressure drop and signal the spinal cord to constrict peripheral vessels"],
  ["Chemoreceptors detect PaO₂, PaCO₂, and pH changes to regulate breathing; they are not the primary short-term blood pressure reflex sensors",
   "The Bainbridge reflex (atrial stretch receptors) responds to high venous return (volume), not low arterial pressure, and increases HR to handle increased preload",
   "Baroreceptors are in the carotid sinus and aortic arch (arterial), not in pulmonary vessels, and signal the medulla (NTS), not the spinal cord directly"],
  "Baroreceptor reflex: BP↓ → less carotid/aortic stretch → NTS receives less inhibitory input → nucleus ambiguus (parasympathetic) inhibited + RVLM (sympathetic) activated → ↑HR, ↑SV, ↑vasoconstriction → BP restored. Phenylephrine raises BP → baroreceptor activates → reflex bradycardia.",
  "Baroreceptor reflex: carotid sinus + aortic arch → medulla → autonomic output. BP↑ → reflex bradycardia. BP↓ → reflex tachycardia.",
  "Thinking the baroreceptor reflex is slow; it acts within seconds and is the primary acute blood pressure regulator.",
  ["RAAS","Orthostatic hypotension","Autonomic nervous system"],[]),

  mk(2,"Physiology","Renal",[
    "Aldosterone is released in response to high angiotensin II and high plasma K⁺. In the collecting duct, which two proteins does aldosterone upregulate to retain sodium?",
    "A patient takes spironolactone (aldosterone antagonist) for hypertension. Which electrolyte changes are expected in plasma?",
  ],
  "aldosterone upregulates ENaC (epithelial sodium channel) on the apical membrane and Na⁺/K⁺-ATPase on the basolateral membrane of principal cells, increasing Na⁺ reabsorption and K⁺ secretion",
  ["aldosterone activates NKCC2 in the thick ascending limb to reabsorb Na⁺, Cl⁻, and K⁺ together",
   "aldosterone opens aquaporin-2 channels to reabsorb water alongside Na⁺ in the collecting duct",
   "aldosterone activates Na⁺/H⁺ exchangers (NHE3) in the proximal tubule to reabsorb sodium in exchange for protons"],
  ["NKCC2 is the target of loop diuretics (furosemide) in the thick ascending limb; aldosterone acts on the collecting duct, not the thick ascending limb",
   "Aquaporin-2 insertion is regulated by ADH (vasopressin), not aldosterone; aldosterone regulates Na⁺ transport independent of water channel insertion",
   "NHE3 in the proximal tubule is regulated by angiotensin II and catecholamines, not directly by aldosterone; aldosterone's principal target is the collecting duct"],
  "Aldosterone (mineralocorticoid): binds intracellular receptor in collecting duct principal cells → gene transcription → ↑ENaC (apical Na⁺ entry) + ↑Na⁺/K⁺-ATPase (basolateral Na⁺ exit) → Na⁺ retained, K⁺ secreted. Spironolactone blocks aldosterone receptor → Na⁺ wasting + K⁺ retention (hyperkalemia).",
  "Aldosterone: ENaC + Na⁺/K⁺-ATPase in collecting duct → Na⁺ in, K⁺ out. Spironolactone → hyperkalemia.",
  "Confusing aldosterone's site (collecting duct principal cells) with furosemide's site (thick ascending limb NKCC2).",
  ["RAAS","ADH","Loop diuretics"],[]),

  mk(2,"Physiology","Endocrinology",[
    "A patient with Graves' disease has TSH-receptor antibodies that constitutively stimulate the thyroid. Which feedback loop is disrupted, and what hormone levels result?",
    "Thyroid hormones increase BMR, oxygen consumption, and heart rate. Which mechanism explains how T3 exerts most of its effects within target cells?",
  ],
  "the hypothalamic-pituitary-thyroid (HPT) axis negative feedback is bypassed; TSH is suppressed (low) because high T3/T4 feeds back on the pituitary, but thyroid activity remains high due to TSH-receptor antibody stimulation",
  ["TSH receptor antibodies activate the thyroid independently of TRH, so TRH increases compensatorily while TSH rises to match",
   "the feedback loop is intact; both TSH and T3/T4 rise proportionally as the TSH receptor antibodies increase receptor sensitivity",
   "the HPT axis is disrupted at the hypothalamic level; CRH (not TRH) is suppressed by elevated thyroid hormones"],
  ["TSH is suppressed because high circulating T3/T4 inhibits pituitary thyrotrophs; TRH may also decrease, not increase",
   "Negative feedback means high T3/T4 suppresses TSH; they do not rise proportionally; suppressed TSH with elevated T3/T4 is the diagnostic hallmark of primary hyperthyroidism",
   "The hypothalamic-pituitary-thyroid axis uses TRH (thyrotropin-releasing hormone), not CRH (corticotropin-releasing hormone); CRH regulates cortisol, not thyroid hormones"],
  "HPT axis: TRH (hypothalamus) → TSH (anterior pituitary) → T3/T4 (thyroid) → negative feedback on both. Graves' disease: TSH-receptor IgG antibody → constitutive T3/T4 production → T3/T4 high → TSH suppressed (negative feedback intact at pituitary level).",
  "Graves' disease: TSH-R antibody → high T3/T4 + suppressed TSH. T3: nuclear receptor → gene transcription → ↑BMR.",
  "Thinking TSH rises in hyperthyroidism; primary hyperthyroidism always suppresses TSH via negative feedback.",
  ["Thyroid hormone synthesis","Iodine metabolism","Hypothyroidism"],[]),

  mk(2,"Physiology","Respiratory",[
    "A premature infant at 28 weeks gestation is born with respiratory distress syndrome (RDS). Which deficiency causes alveolar collapse, and which treatment is given?",
    "A patient has a pulmonary embolism blocking flow to the right lower lobe. V/Q in that region approaches infinity. Which gas exchange abnormality results?",
  ],
  "surfactant deficiency (primarily DPPC, dipalmitoylphosphatidylcholine) causes alveolar surface tension to remain high, leading to alveolar collapse; exogenous surfactant is given as treatment",
  ["a deficiency in type I pneumocytes causes gas exchange failure; treatment involves supplemental O₂ to restore diffusion",
   "alveolar macrophage deficiency prevents clearance of fluid, which floods the alveoli; treatment is diuresis",
   "Clara cell deficiency reduces mucus clearance, causing airway obstruction; treatment is bronchodilators"],
  ["Type I pneumocytes provide the thin barrier for gas exchange; RDS is caused by surfactant deficiency from type II pneumocyte immaturity, not type I cell loss",
   "Alveolar edema can cause RDS in adults, but neonatal RDS is specifically due to surfactant deficiency; diuresis is not the primary treatment for neonatal RDS",
   "Clara cells produce Club cell secretory protein in terminal bronchioles; surfactant is produced by type II pneumocytes; RDS is not a mucus/airway obstruction problem"],
  "Surfactant (type II pneumocytes): DPPC reduces surface tension (LaPlace: P = 2T/r → small alveoli stable). Without surfactant, small alveoli collapse (atelectasis). Fetal lung matures ~35 weeks. Treatment: exogenous surfactant + corticosteroids to mothers at risk of preterm delivery.",
  "Surfactant: reduces alveolar surface tension → prevents collapse. Produced by type II pneumocytes. Deficient in preterm infants → RDS.",
  "Confusing type I pneumocytes (thin for gas exchange) with type II pneumocytes (produce surfactant); RDS involves type II failure.",
  ["V/Q mismatch","Pulmonary compliance","Alveolar gas equation"],["P = 2T/r (LaPlace); surfactant lowers T"]),

  mk(2,"Immunology","Innate and Adaptive Immunity",[
    "A patient with a defect in Toll-like receptor (TLR) signaling repeatedly develops severe bacterial infections from gram-negative bacteria. Which component of the bacteria fails to be recognized?",
    "NK cells kill virus-infected cells that downregulate MHC class I. Which principle explains why MHC I downregulation makes cells vulnerable to NK killing?",
  ],
  "lipopolysaccharide (LPS), which is recognized by TLR-4 on innate immune cells; without this recognition, the inflammatory response against gram-negative bacteria is severely impaired",
  ["peptidoglycan from gram-negative bacteria is not recognized because TLR-2 (not TLR-4) is defective",
   "flagellin from gram-negative bacteria fails to be detected because the adaptive immune system cannot mount an IgG response",
   "the capsule polysaccharide of gram-negative bacteria evades innate detection because capsule recognition requires complement alone"],
  ["Peptidoglycan is recognized by TLR-2; LPS (endotoxin) is recognized by TLR-4; the question specifies gram-negative bacteria and TLR defects",
   "Flagellin is recognized by TLR-5; the adaptive immune response is not the defect in this scenario; TLR signaling is innate immunity",
   "Complement can be activated by capsule (alternative/lectin pathway), but TLR-4/LPS recognition is the primary innate response to gram-negative bacteria; capsule evasion is a separate virulence mechanism"],
  "Innate immunity uses pattern recognition receptors (PRRs) including TLRs to detect PAMPs. TLR-4: LPS (gram-negative). TLR-2: peptidoglycan (gram-positive). TLR-3/7/8/9: viral RNA/DNA. TLR signaling activates NF-κB → cytokines → inflammation. Missing TLR-4 → LPS not sensed → impaired response.",
  "TLR-4: LPS (gram-negative). TLR-2: peptidoglycan (gram-positive). TLR-3/7/8/9: viral nucleic acids. Missing TLR = PAMP not detected.",
  "Confusing TLR-2 (peptidoglycan) with TLR-4 (LPS); gram-negative bacteria are distinguished by their LPS.",
  ["Complement system","Adaptive immunity","Cytokines"],[]),

  mk(2,"Immunology","Adaptive Immunity",[
    "A CD8⁺ cytotoxic T lymphocyte (CTL) recognizes a viral peptide presented on MHC class I of an infected cell. Which cells can present antigen to CTLs, and what is the killing mechanism?",
    "A patient's MHC class II molecules are nonfunctional. Which adaptive immune responses are most severely impaired?",
  ],
  "all nucleated cells express MHC class I and can present endogenous peptides to CD8⁺ CTLs; CTLs kill by releasing perforin (pores) and granzymes (proteases that activate caspases)",
  ["only professional antigen-presenting cells (dendritic cells, macrophages, B cells) can present to CD8⁺ CTLs via MHC I",
   "CD8⁺ CTLs kill by secreting IgG antibodies that opsonize infected cells for macrophage phagocytosis",
   "CTLs kill infected cells by triggering complement deposition on MHC I-peptide complexes"],
  ["All nucleated cells express MHC I; professional APCs are distinguished by MHC II expression (for CD4⁺ helper T cells), not by exclusive MHC I expression",
   "Antibody secretion is performed by plasma B cells; CD8⁺ CTLs kill directly via perforin/granzyme, not via antibody",
   "Complement is activated by antibodies or directly by pathogens; CTLs use cell-mediated cytotoxicity, not complement, to kill infected cells"],
  "MHC I (HLA-A/B/C): on all nucleated cells; presents endogenous peptides to CD8⁺ CTLs. MHC II (HLA-DR/DP/DQ): on professional APCs only; presents exogenous peptides to CD4⁺ helper T cells. CTL killing: perforin forms pores → granzymes enter → caspase activation → target cell apoptosis.",
  "MHC I: all nucleated cells → CD8⁺ CTLs. MHC II: APCs only → CD4⁺ helper T cells. CTL kills via perforin + granzymes.",
  "Thinking only professional APCs express MHC I; all nucleated cells do — that's why viruses must hide from CTLs by downregulating MHC I.",
  ["NK cells","B cell activation","Antibody classes"],[]),

  mk(2,"Immunology","Adaptive Immunity",[
    "IgM antibodies are the first to appear after initial antigen exposure, but IgG dominates in secondary responses. Which process is responsible for the class switch from IgM to IgG?",
    "A patient with a mutation in AID (activation-induced cytidine deaminase) cannot perform somatic hypermutation. What consequence does this have for vaccine efficacy?",
  ],
  "class switch recombination (CSR), directed by T-helper cytokines (IL-4 for IgE/IgG1, IFN-γ for IgG2, TGF-β for IgA), rearranges constant region genes while preserving the same antigen-binding variable region",
  ["somatic hypermutation in the germinal center introduces point mutations into constant region genes, changing the antibody class without altering antigen specificity",
   "VDJ recombination is repeated after antigen exposure to select for new constant regions appropriate for secondary immune responses",
   "the variable region is translated with different constant region sequences by alternative mRNA splicing in activated B cells"],
  ["Somatic hypermutation introduces mutations into variable regions to increase affinity (affinity maturation), not to change antibody class; CSR changes the constant region",
   "VDJ recombination occurs only once in bone marrow during B cell development; it does not repeat after antigen exposure; CSR rearranges constant region segments",
   "IgM vs IgG expression can involve alternative splicing (membrane vs secreted form), but class switching is a DNA recombination event, not just alternative splicing of constant regions"],
  "Class switch recombination: DNA recombination replaces Cμ (IgM) with downstream constant region genes (Cγ, Cε, Cα). Variable region preserved → same antigen specificity, different effector function. Driven by T-helper cytokines. AID enzyme required for both CSR and somatic hypermutation.",
  "CSR: Cμ → Cγ/Cε/Cα via DNA recombination. Preserves V region. Driven by T-helper cytokines. AID required.",
  "Confusing class switch recombination (constant region DNA change) with somatic hypermutation (variable region point mutations for affinity).",
  ["Germinal center reaction","Affinity maturation","Primary vs secondary immune response"],[]),

  mk(2,"Genetics","Inheritance",[
    "A pedigree shows a trait appearing in every generation, affecting males and females equally, with at least one affected parent in every case. Which pattern of inheritance is most consistent?",
    "A trait appears only in males in a pedigree. Affected fathers never have affected sons, but all daughters of affected fathers are carriers. Which inheritance pattern is this?",
  ],
  "autosomal dominant inheritance, characterized by vertical transmission in every generation, equal sex ratio of affected individuals, and a 50% risk to offspring of an affected parent",
  ["autosomal recessive inheritance, where the trait can appear in every generation if carriers are common in the population",
   "X-linked recessive inheritance, which could produce the described pattern if many females are heterozygous carriers",
   "mitochondrial inheritance, where all children of an affected mother are affected and the trait appears in every generation"],
  ["Autosomal recessive traits typically skip generations (carrier parents unaffected); appearing in every generation with an affected parent each time strongly suggests dominant, not recessive",
   "X-linked recessive would spare many females (who must be homozygous to be affected) and affect all males with the allele; equal sex ratio rules out X-linked recessive",
   "Mitochondrial inheritance is strictly maternal (affected mothers → all children affected); the described pedigree shows affected fathers with unaffected children, inconsistent with mitochondrial"],
  "Autosomal dominant: affected individual → 50% affected offspring. Each generation affected. Equal sex distribution. One mutant allele sufficient. Examples: Huntington's, BRCA2 (partial penetrance), familial hypercholesterolemia.",
  "Autosomal dominant: vertical, equal sex ratio, 50% risk, one affected parent always present.",
  "Calling multigenerational pedigrees mitochondrial when affected fathers are present; mitochondrial inheritance is strictly maternal.",
  ["Penetrance and expressivity","X-linked dominant","Genetic anticipation"],[]),

  mk(2,"Genetics","Population Genetics",[
    "A researcher studies a gene in a population of 50 breeding individuals on a remote island. Over 10 generations, one allele disappears despite being selectively neutral. Which mechanism explains this?",
    "Sickle cell trait (HbAS) is more common in malaria-endemic regions than expected for a recessive disease. Which evolutionary mechanism maintains the sickle allele at high frequency?",
  ],
  "genetic drift, which causes random changes in allele frequencies that are larger in small populations; in small populations, chance events can fix or eliminate alleles regardless of fitness",
  ["natural selection against the allele, which is less efficient in small populations and requires many generations to eliminate neutral alleles",
   "the founder effect, which reduces genetic variation after a large population colonizes a new area by sampling a small number of individuals",
   "gene flow from neighboring populations, which dilutes the allele frequency until it disappears below detection"],
  ["Neutral alleles are not subject to natural selection by definition; drift explains loss of neutral alleles in small populations",
   "The founder effect describes the bottleneck when a small group establishes a new population; the ongoing small population described (50 individuals over 10 generations) is genetic drift, not founder effect per se",
   "Gene flow from neighboring populations would introduce, not eliminate, alleles unless the neighboring population has zero frequency of that allele; the mechanism described is stochastic, not flow-dependent"],
  "Genetic drift: random sampling errors in allele frequency. Larger effect in small populations. Can fix or eliminate alleles by chance. Bottleneck effect (sudden population crash) and founder effect (small group colonizes new area) are special cases of drift.",
  "Genetic drift: random allele frequency changes; larger effect in smaller populations. Can fix neutral alleles. Heterozygote advantage: maintains deleterious alleles (sickle cell in malaria).",
  "Confusing genetic drift (random) with natural selection (non-random); drift affects all alleles including neutral ones.",
  ["Hardy-Weinberg","Natural selection","Bottleneck effect"],[]),

];
